name: bloc_application
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  cupertino_icons: ^1.0.2
  rxdart: ^0.27.4
  flutter_bloc: 7.0.1
  get_it: ^7.2.0
  mocktail: ^0.2.0
  equatable: ^2.0.3
  
dev_dependencies:
  bloc_test: ^8.0.2
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  